### PR TITLE
Laravel 10 compatibility

### PR DESCRIPTION
**Pull request by howdu**

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@howdu Can you also update the workflow file please?

**Comment by howdu** [comment]
@ryangjchandler sure no problem

**Comment by ryangjchandler** [comment]
Thanks @howdu , had to make a few extra changes to keep the CI happy.

**Comment by ryangjchandler** [comment]
Use v0.5.0 for Laravel 10.x :)

**Pull request merged**
