### PR TITLE
Allow grouping Navigation resource

### PR DESCRIPTION
**Pull request by bumbummen99**
Allows grouping the navigation resource by simply reconfiguring it.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@bumbummen99 Have you created a fork of this package with translations?

**Comment by bumbummen99** [comment]
> @bumbummen99 Have you created a fork of this package with translations and submitted those changes as a PR? Seems like a lot of changes to make the resource groupable.

Yeah the one you closed. Used wrong branch for PR

**Comment by ryangjchandler** [comment]
Navigation group can be configured already, Filament provides that functionality out of the box. No changes are needed to the package.

```php
NavigationResource::navigationGroup('My Group');
```

Put that in a ServiceProvider's `boot` method.

**Comment by bumbummen99** [comment]
> Navigation group can be configured already, Filament provides that functionality out of the box. No changes are needed to the package.
> 
> ```
> NavigationResource::navigationGroup('My Group');
> ```
> 
> Put that in a ServiceProvider's `boot` method.

Thanks for the tipp, i was told on Discord that this has to be patched into the package.

**Comment by ryangjchandler** [comment]
@bumbummen99 We haven't documented that method yet, I don't think. Will note it to Dan.

**Pull request closed without merging**
