### PR TITLE
[Feature] Add sorting items

### PR DESCRIPTION
**Pull request by bumbummen99**

### CODE REVIEW

**Comment by ryangjchandler** [comment]
Were you thinking of sorting the actual navigation models, or the navigation items?

**Comment by bumbummen99** [comment]
> Were you thinking of sorting the actual navigation models, or the navigation items?

The items, the overlay buttons did not show up for me

**Comment by ryangjchandler** [comment]
I don't see how your PR is related then. You don't need any sorting packages.

**Comment by bumbummen99** [comment]
> I don't see how your PR is related then. You don't need any sorting packages.

That is why i closed it :)

**Pull request closed without merging**
